//------------------------------------------------------------------------
// Copyright(c) 2022 LumyLumyStudio.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"RoutePePe.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"RoutePePe VST3 (64Bit)"
#else
#define stringFileDescription	"RoutePePe VST3"
#endif
#define stringCompanyName		"LumyLumyStudio\0"
#define stringLegalCopyright	"Copyright(c) 2022 LumyLumyStudio."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
